name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test tests/LINTelligent.UnitTests/LINTelligent.UnitTests.csproj --no-build --configuration Release

      - name: Run Integration Tests
        run: dotnet test tests/LINTelligent.IntegrationTests/LINTelligent.IntegrationTests.csproj --no-build --configuration Release

