name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "src/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  verify-compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore and Build
        run: |
          dotnet restore src/LINTelligent.csproj
          dotnet build src/LINTelligent.csproj --no-restore --configuration Release
