name: Migrate Database
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        working-directory: LINTelligent.Api/src
        run: dotnet restore
        
      - name: Install EF Core tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply migrations to production
        working-directory: LINTelligent.Api/src
        run: dotnet ef database update --connection "${{ secrets.PROD_DB_CONNECTION_STRING }}"
